# Generated by Django 5.1.3 on 2024-12-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the event', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the event')),
                ('event_image', models.TextField(blank=True, help_text='Image or banner for the event', null=True)),
                ('event_type', models.CharField(choices=[('seminar', 'Seminar'), ('workshop', 'Workshop'), ('webinar', 'Webinar'), ('counseling', 'Counseling Session'), ('fair', 'Education Fair')], help_text='Type of event', max_length=50)),
                ('start_date', models.DateField(help_text='Start date of the event')),
                ('end_date', models.DateField(blank=True, help_text='End date of the event (if applicable)', null=True)),
                ('start_time', models.TimeField(blank=True, help_text='Start time of the event', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='End time of the event', null=True)),
                ('location', models.CharField(help_text='Location or platform (for online events)', max_length=255)),
                ('is_online', models.BooleanField(default=False, help_text='Is this event held online?')),
                ('registration_required', models.BooleanField(default=True, help_text='Is registration required?')),
                ('registration_link', models.URLField(blank=True, help_text='Registration link for online registration', null=True)),
                ('contact_email', models.EmailField(help_text='Contact email for queries', max_length=254)),
                ('max_participants', models.PositiveIntegerField(blank=True, help_text='Maximum number of participants', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the event was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the event was last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Is this event active?')),
            ],
        ),
    ]
