# Generated by Django 5.1.3 on 2024-12-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_enquiry_delete_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
