# Generated by Django 5.1.3 on 2024-12-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('duration_in_weeks', models.PositiveIntegerField(help_text='Duration of the course in weeks')),
                ('fee', models.DecimalField(decimal_places=2, help_text='Course fee in local currency', max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
