# Generated by Django 5.1.3 on 2024-12-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
